version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "username"
    assignees:
      - "username"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    target-branch: "develop"
    versioning-strategy: "auto"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "username"
    assignees:
      - "username"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    target-branch: "develop"
    rebase-strategy: "auto"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "username"
    assignees:
      - "username"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    target-branch: "develop"
    rebase-strategy: "auto" 